### ISSUE TITLE
Exception whem using app for telegram

### ISSUE THREAD

**Issue by AntonVMakarov** [datalust/helm.datalust.co#52]
Hi, I am using seq on Linux Ubuntu 22.04 LTS. I also use app to send information to telegram bot. Periodically I get an exception:
--------------------------------
Telegram.Bot.Exceptions.RequestException: Request timed out
 ---> System.Threading.Tasks.TaskCanceledException: The request was canceled due to the configured HttpClient.Timeout of 100 seconds elapsing.
 ---> System.TimeoutException: A task was canceled.
 ---> System.Threading.Tasks.TaskCanceledException: A task was canceled.
   at System.Threading.Tasks.TaskCompletionSourceWithCancellation`1.WaitWithCancellationAsync(CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.HttpConnectionWaiter`1.WaitForConnectionAsync(Boolean async, CancellationToken requestCancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithVersionDetectionAndRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)
   --- End of inner exception stack trace ---
   --- End of inner exception stack trace ---
   at System.Net.Http.HttpClient.HandleFailure(Exception e, Boolean telemetryStarted, HttpResponseMessage response, CancellationTokenSource cts, CancellationToken cancellationToken, CancellationTokenSource pendingRequestsCts)
   at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)
   at Telegram.Bot.TelegramBotClient.<MakeRequestAsync>g__SendRequestAsync|22_0[TResponse](HttpClient httpClient, HttpRequestMessage httpRequest, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at Telegram.Bot.TelegramBotClient.<MakeRequestAsync>g__SendRequestAsync|22_0[TResponse](HttpClient httpClient, HttpRequestMessage httpRequest, CancellationToken cancellationToken)
   at Telegram.Bot.TelegramBotClient.MakeRequestAsync[TResponse](IRequest`1 request, CancellationToken cancellationToken)
   at Telegram.Bot.TelegramBotClientExtensions.SendTextMessageAsync(ITelegramBotClient botClient, ChatId chatId, String text, Nullable`1 parseMode, IEnumerable`1 entities, Nullable`1 disableWebPagePreview, Nullable`1 disableNotification, Nullable`1 replyToMessageId, Nullable`1 allowSendingWithoutReply, IReplyMarkup replyMarkup, CancellationToken cancellationToken)
   at Seq.App.Telegram.TelegramReactor.OnAsync(Event`1 evt) in C:\projects\seq-app-telegram\src\Seq.App.Telegram\TelegramReactor.cs:line 83
   at SeqCli.Apps.Hosting.AppContainer.SendTypedEventAsync(String clef) in C:\projects\seqcli\src\SeqCli\Apps\Hosting\AppContainer.cs:line 113
--------------------------------
Are there any ideas why this exception happens? It hangs the server and i need to reboot it every time...

**Comment by nblumhardt** [comment]
Hi Anton, thanks for dropping us a line.

This looks most like an issue with the Telegram bot; I'd start over in [Seq.App.Telegram](https://github.com/stdray/Seq.App.Telegram/tree/master) and look at updating the version of the `Telegram.Bot` package dependency there, as well as potentially adding a retry loop (Polly?) [around the line that sends the message](https://github.com/stdray/Seq.App.Telegram/blob/master/src/Seq.App.Telegram/TelegramReactor.cs#L83).

If the entire server hangs I'd suspect something else going on, Seq apps run in separate processes and usually can't cause the main Seq process to fail - interested in any more details you can share, if you think that may be happening.

Best regards,
Nick

**Comment by AntonVMakarov** [comment]
Thanks for answer Nick. I figured out what was going on. The server was not powerful enough, when I increased the server resources, the problem disappeared...
Anton, best regards.
